apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
data:
  DOCKER_INFLUXDB_INIT_MODE: "setup"
  DOCKER_INFLUXDB_INIT_USERNAME: "admin"
  DOCKER_INFLUXDB_INIT_PASSWORD: "mySuP3rS3cr3tT0keN"
  DOCKER_INFLUXDB_INIT_ORG: "iosmcn"
  DOCKER_INFLUXDB_INIT_BUCKET: "pm-logg-bucket"

