apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust storage size as needed
  storageClassName: local-path

